### ISSUE TITLE
Keyboard shortcut?

### ISSUE THREAD

**Issue by seanmadsen** [captnfab/FireTitle#10]
Is there a way I can add a keyboard shortcut to activate FireTitle?

**Comment by captnfab** [comment]
There's already a keyboard shortcut: [Ctrl] + [;]
Unfortunately, the add-on does not allow for user-customization of the shortcut.
If you want to build your own version of firetitle with a custom keyboard shortcut, you can modify the source code here: https://github.com/captnfab/FireTitle/blob/master/chrome/content/firetitle.xul#L38

**Comment by seanmadsen** [comment]
This is really helpful. Thank you. I had a different addon ("Zoom Page") which already mapped `Ctrl` + `;`, but thankfully I was able to edit the settings for Zoom Page and remove the mapping. Now I'm happily using `Ctrl` + `;` to set custom page titles. This addon is *sooo* helpful!!! Thank you!! :clap:

**Comment by captnfab** [comment]
Happy to help! Thanks for your support :)
