### ISSUE TITLE
FireTitle 0.5.5-1.1… unreliable with Firefox 55.0.3 and 56.0b10

### ISSUE THREAD

**Issue by grahamperrin** [captnfab/FireTitle#14]
55.0.3 (64-bit) on FreeBSD-CURRENT, 56.0b10 (64-bit) on Kubuntu. 

With a preference for `nt` and on-demand restoration of hundreds of tabs across twelve windows, it's common to find most windows improperly titled. 

Workaround: click away from the affected tab, then back to the tab … but if you don't wait long enough, then another tab will be affected.

**Comment by captnfab** [comment]
Crap.
Ok, first, the add-on isn't supposed to be installable on FF 55, the minimum version requirement is 56 since the API used is only present since FF 56.0b7.
However, I'm more sad about the unreliability with Firefox 56.0b10.
Do you have a way to reproduce the problem deterministically? What happen exactly when the title is wrong? Does the window shows the default title? Does it show another tab's title? Does it show only "Mozilla Firefox"?
Thanks for your report.

**Comment by grahamperrin** [comment]
I made a long screen recording of the issue with heavily extended Firefox 55.0.3. 

Then, some simple shots of the issue with minimally extended 56.0b10 – FireTitle and [Session Manager](https://addons.mozilla.org/addon/session-manager/) alone. Work in progress. 

----

For now: I don't know whether these are contributory to the issue, but it's remarkable that not-logged-in (NLI) views of these two URLs (second and third tabs in a single-group four-tab window) present a title only whilst loading – no title when loaded: 

- <https://discordapp.com/channels/324090228497448961/325059176759820310>
- <https://discordapp.com/channels/350004786915180548/350004787481280524>

**Comment by grahamperrin** [comment]
A very short recording of an affected window with heavily extended 55.0.3: 

https://vimeo.com/233261714

**Comment by grahamperrin** [comment]
With minimally extended 56.0b10: 

![2017-09-11 05 48 49](https://user-images.githubusercontent.com/192271/30260707-df485b82-96c0-11e7-8174-3bc2b304b9a2.png)

![2017-09-11 05 49 17](https://user-images.githubusercontent.com/192271/30260765-3421afd2-96c1-11e7-851e-fbab24c06d77.png)

![2017-09-11 05 49 44](https://user-images.githubusercontent.com/192271/30260771-3ba1e876-96c1-11e7-9f19-de800a304da0.png)

**Comment by captnfab** [comment]
Ok, thanks, I've been able to reproduce the bug too. Apparently, some signal of "page loaded" is fired earlier now, so the page title is read before it's loaded...

**Comment by grahamperrin** [comment]
Great! 

Incidentally, I vaguely recall _occasional/rare_ title problems with Firefox 54.x. Maybe the sense of randomness grew during that period. Problems became much more noticeable when 55.0 arrived. 

If there's a reasonably easy way to identify the Mozilla changeset(s) underlying this issue, I'll be glad to know. 

Many thanks

**Comment by captnfab** [comment]
The release notes give some clues: https://www.mozilla.org/en-US/firefox/55.0/releasenotes/

**Comment by grahamperrin** [comment]
Thanks. 

I wondered whether the Firefox 55.0 beginning (or exacerbation) of this issue affecting FireTitle arose from work around Mozilla bug [906076 - (lazytabs) Virtual tabs - lazily create linkedBrowser and other dependent elements for tabbrowser tabs to improve startup performance](https://bugzilla.mozilla.org/show_bug.cgi?id=906076). Related: 

- [The New Firefox and Ridiculous Numbers of Tabs – Dietrich Ayala](https://metafluff.com/2017/07/21/i-am-a-tab-hoarder/) (2017-07-21). 

I sped through Mozilla's 906076 and some linked items. A few mentions of titles, but I could not see anything that might have led to this issue 14.  I'm not a developer, just curious `:-)`

**Comment by captnfab** [comment]
I think the bug is fixed in commit bf1f423c081ec33000303874ae1580c356fef608, I uploaded new FireTitle version to addons.mozilla.org.
If you have a developper version of Firefox, you can generate the xpi with make and try it.

**Comment by grahamperrin** [comment]
👍 fix confirmed, thanks! 

## Before a quit

![2017-09-13 14 57 37 plasma](https://user-images.githubusercontent.com/192271/30391092-2a524386-98b0-11e7-9488-91833cd8c430.png)

## Restoring the session

The titles appear, disappear, then reappear at load time. 

![2017-09-13 15 00 16 plasma](https://user-images.githubusercontent.com/192271/30391126-44cad6ce-98b0-11e7-9df5-0d46b5319e07.png) ![2017-09-13 15 01 09 plasma](https://user-images.githubusercontent.com/192271/30391138-4ced822a-98b0-11e7-997a-dba4ca04b31d.png) ![2017-09-13 15 01 23 plasma](https://user-images.githubusercontent.com/192271/30391140-508cee2a-98b0-11e7-821d-2976cae18761.png) ![2017-09-13 15 01 42 plasma](https://user-images.githubusercontent.com/192271/30391146-5464bde8-98b0-11e7-8bdd-ae29a36de226.png) ![2017-09-13 15 02 14 plasma](https://user-images.githubusercontent.com/192271/30391155-5892081c-98b0-11e7-82af-13a07f043ae0.png)
