### ISSUE TITLE
"New Windows" shows instead of blank

### ISSUE THREAD

**Issue by starcat13** [captnfab/FireTitle#21]
I have empty "Window's name" field, but in windows titles I see "New Window".
How can i have it empty by default?

**Comment by captnfab** [comment]
Right, if window's name evaluates to false, default name is used.
I'll change that for "if window's name is undefined".

**Comment by captnfab** [comment]
New version submitted to addons.mozilla.org. 0.1.4 (b0cb2a7dcf8a20369fc56d85fc735dea3436df61) fixing this bug.
