### ISSUE TITLE
Focus in "Window's name" form field when having clicked the icon

### ISSUE THREAD

**Issue by celemon** [captnfab/FireTitle#22]
It would be useful if the form field "Window's name" was in focus (with any preexisting form field text preselected) when the popup window opens on clicking the icon in the top bar. Entering a new title will be much quicker, with the user just having to click the icon and write.

**Comment by captnfab** [comment]
Indeed. I'm not exactly sure how to do that, but I'll try to add this behavior for the next release.

**Comment by celemon** [comment]
Maybe example 5 in https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Focus_and_Selection (?)

Sorry that I am sitting here and just sending pages: have to work and have not yet tried to download and compile any code (just added a user to input on your add on which I love).

**Comment by captnfab** [comment]
I had to use a hack for the focus to be set properly on the current window's name input field.
But hopefully, it now works (version 0.1.11, just released.)
