### ISSUE TITLE
Window names are sometimes lost on browser restart

### ISSUE THREAD

**Issue by alvaro-cuesta** [captnfab/FireTitle#23]
Pretty much what the title says. On Firefox restart every window name reverts to "New Window" except the left-most one (as in taskbar position, which probably corresponds with the first opened window).

This is _not_ #16 since the name that remains is correct.

Windows 10, FF 57.0.1, Crappy Firetitle 0.1.5

Let me know how can I help you debug this.

**Comment by captnfab** [comment]
Crap. I'll try to reproduce that and fix it as soon as possible. I'll ping you if I need help to reproduce the bug.

**Comment by tomforwood** [comment]
Same here, except all the window titles are being overwritten with the title of one window. Probably the last window to have focus when I quit firefox

**Comment by captnfab** [comment]
Thx tomforwood, So, the bug is confirmed. I'll try to fix it ASAP…

**Comment by rsalmei** [comment]
Unfortunately it isn't working for me too. With it all updated, macOS 10.13.2, Firefox 57.0.1 and Crappy 0.1.5.
Sometimes only my "main" window gets its name back (first one), sometimes none of them...

**Comment by frasierlinde** [comment]
Same here. And I just noticed that as each window opens, it shows its previous title for a split second before resetting to "New Window."
W7SP1, FF 57.0.4, CFT 0.1.5

**Comment by alvaro-cuesta** [comment]
To debug this you can go to `about:debugging`, enable extension debugging and then click `Debug` on FireTitle (and accept the connection request).

Then just paste this on the debugging console:

```js
browser.windows.getAll()
.then(ws => Promise.all(ws.map(({ id, title }) => Promise.all([
  id,
  title,
  browser.sessions.getWindowValue(id, 'win_name'),
]))))
.then(ws => ws.forEach(([ id, title, name ]) => console.log(`[${id}] ${title} = ${name}`)))
```

It list window ids, their title and the saved title.

For me the window ids didn't change across restarts, but the saved names were overwritten, which means at some point `browser.sessions.setWindowValue` was being called with the default name, overwriting the saved settings.

While debugging this I found sometimes _some_ of my window names were restored and other didn't. I'm pretty sure this is a race condition regarding events.

I think I found the culprit: https://github.com/captnfab/FireTitle/blob/fb91f288b3574b26993eb8a9b9f4dc12d8eafa98/firetitle/background.js#L45-L52

I'm not that knowledgeable about WebExtensions but I hope this can help someone else fix the issue.

**Comment by jpfleury** [comment]
I too have this bug with Firefox 59 and Firefox 60 beta. Every time I restart the browser, all but one or two windows lose their custom name.

**Comment by cnorman-enphase** [comment]
I am also having this problem.  60.0.2 on macOS 10.12.6.  Pretty much as jpfleury described.  Is there a patch available?

**Comment by captnfab** [comment]
Not yet, I'm sorry I haven't had time to work on it. I'll try to fix that tomorrow.

**Comment by paolo-crisafulli** [comment]
For the record, I also get this issue: Firefox 60.0, Ubuntu 16.04.4 LTS

Too bad, I really like this plugin (not so "crappy" indeed): combined with the Multiple Tab Handler plugin, it helps me a lot in the mourning process for Tab Groups :-)

**Comment by captnfab** [comment]
I kind of blindly tried to solve this bug (since I can't reproduce it).
Version 0.1.6 should avoid the race condition reseting the title on restore.
Please try it and tell me if it does work.

**Comment by cnorman-enphase** [comment]
Woops, I was wrong.  I restarted my Mac and loaded Firefox and... only 2 got restored. the Rest are named "New Window"... :(

**Comment by captnfab** [comment]
:(
I'll try something else.

**Comment by starcat13** [comment]
I have the same problem under Windows, can test too. Or provide any extra information, if it helps.

**Comment by captnfab** [comment]
@starcat13: I'm quite sure the bug will still be there for you too. I just have to find where that race condition happens...
But thanks, I'll try to release a new version the next hour and I'll notify you so that you can do some testing.

**Comment by starcat13** [comment]
thank you!
Not a critical bug for me, I rarely restart FF.

**Comment by captnfab** [comment]
0.1.8 is available :)

**Comment by captnfab** [comment]
@starcat13 @cnorman-enphase : any change? did it fix it?

**Comment by starcat13** [comment]
I tried restart FF and even reboot my computer several times and each time all window names were restored.
Thank you again!

**Comment by captnfab** [comment]
Great, thanks for the testing!

**Comment by ExchangeGuy** [comment]
Works for me! 

All CFT Titles (8 named windows, 100+ tabs) restored in three scenarios: Firefox updated/restarted (by FF), killed the FF process then started FF, restarted computer (Win10). Worked great after each!  (Would always fail before, I would loose all Titles.

This update is very, very much appreciated. Now a major stumbling block after 57 is gone.

Thanks,
Lee~

P.S. I put five dots..... after any Title I set with CFT. Least visible character (as multiple spaces don't work), gives a little separation between Title..... and everything else.

**Comment by captnfab** [comment]
@ExchangeGuy Thanks for the feedback.

Instead of dots, you can use a non-breaking space https://en.wikipedia.org/wiki/Non-breaking_space
On windows: Alt+0160 or Alt+255
On Linux (depending on keymap): Compose, Space, Space or AltGr+Space or Shift+Space
On macOS: Opt+Space

You can add multiple non-breaking spaces, it works.

**Comment by captnfab** [comment]
@paolo-crisafulli @jpfleury @rsalmei @tomforwood @frasierlinde and others I already notified: I believe this problem is now solved. I apologize for letting such an annoying bug alive for so long :)

**Comment by cnorman-enphase** [comment]
Thank you so much, this is a big advance in the usability of your extension!  I confirm it worked here on macOS Sierra and latest FF mainstream.

Chris Norman
Sr. Engineer, Software Support - Enphase Energy

**Comment by paolo-crisafulli** [comment]
Thank you, seems to work for me too!
