### ISSUE TITLE
CTRL+ ; does not seem to work in CrappyFireTitle

### ISSUE THREAD

**Issue by aishik-0002** [captnfab/FireTitle#24]
Pretty much what the title says. I tried pressing it on different pages but nothing happens.

I'm not sure whether this is a bug or not, since the main page for the addon says : 
>this version lacks some features of the original 

is `CTRL + ;` supposed to work in CrappyFireTitle? 

Because ever since I installed it, it does not seem to be registering at all. 

Is there any other way to rename windows through the add-on? Like through some other key or something

Sorry if this isn't reproducible, maybe it's just me. 

Thanks!

**Comment by starcat13** [comment]
Try Ctrl-,

**Comment by aishik-0002** [comment]
`CTRL-,` works!

 Thank you! 👍

**Comment by captnfab** [comment]
Yeah, at the time of the development of crappy firetitle, the webextension api didn't allow for ; to be used in a shortcut. Dunno if it changed since then…
