### ISSUE TITLE
Add "Profile"

### ISSUE THREAD

**Issue by cocker-cc** [captnfab/FireTitle#26]
Please add the Possibility to display the Firefox-Profile-Name in the Titlebar.

**Comment by JJM02351** [comment]
Yes, please allow usage of the profile name as the windows tab name.  Keeping separate profiles open for multiple user login and access testing, etc. is the primary reason I started using Firefox.

**Comment by captnfab** [comment]
This should be achieved by the last commit.

**Comment by captnfab** [comment]
You can use « p » in the pattern to display the profileName (that you can define in the add-on settings)

**Comment by captnfab** [comment]
@JJM02351 @cocker-cc I hope the feature is implemented the way you expected?

**Comment by cocker-cc** [comment]
Yes it works – as long as there is Content on the Page, and not a blank Page.  But that's another Story, I guess.  Thanks for Your Work!
