### ISSUE TITLE
When the FireTitle button is pressed (or keyboard shortcut), the "Window's name" text field does not have focus

### ISSUE THREAD

**Issue by paolo-crisafulli** [captnfab/FireTitle#32]
Hi Captain,
It would save a bit of effort if the "Window's name" text field was focused by default.
Details:
I love keyboard shortcuts, my current practice is to use C-,
But then I have to press TAB twice to reach the "Window's name" text field :-(

I'm using Firefox 60.0 on Ubuntu 16.04.4 LTS.

Thank you for your help.
Cheers,
Paolo

**Comment by captnfab** [comment]
Hi and thanks for your report.
This bug is duplicate of #22 .

**Comment by paolo-crisafulli** [comment]
I have updated the add-on and the fix works fine for me.
Thank you very much, sorry for the duplication (darn, I was pretty sure I had checked for existing issues!).

**Comment by captnfab** [comment]
No problem, I was planning on trying again to solve this issue anyway :)
