### ISSUE TITLE
Not possible to use multiple spaces?

### ISSUE THREAD

**Issue by ganego** [captnfab/FireTitle#47]
So I just thought about getting rid of the forced crap at the end by just using lots of spaces (and protected spaces as an alternative). 
But that did not work and `"   "` for example turned simply into `" "`. Is this a limitation of the API or does FireTitle do this?

**Comment by captnfab** [comment]
Hi,
I think it's a limitation of the API.
However, you can work around it by using non-breaking spaces instead of spaces.

**Comment by ganego** [comment]
I did (this is what I meant with 'protected spaces') but it did not work.  
But thanks so you post I now tried it again. The problem was, that I just copy & pastes the nbsp and this did not work for whatever reason. Writing every single nbsp with ALT+0160 (Windows) separately works though. Interesting.
