### ISSUE TITLE
Feature: Display number of (loaded) tabs in title

### ISSUE THREAD

**Issue by captnfab** [captnfab/FireTitle#5]
> I would really, really, really like a 'pattern element' for number of tabs in a window.

**Comment by grahamperrin** [comment]
… also, the number of tabs that are _loaded_.

**Comment by captnfab** [comment]
So, Crappy Firetitle can display the number of tabs in a window.
@grahamperrin Loaded tabs are tabs where the page is actually loaded, right?
There probably is a way to check that. I'll have a look at it next time I'm working on the project.

**Comment by grahamperrin** [comment]
For what it's worth: [Tab Tally](https://addons.mozilla.org/addon/tab-tally/) is the closest I have come to finding an extension that _reliably_ counts the number loaded. As far as I can tell: it's accurate whilst the number increases, but does not (maybe can not) count down when an unload occurs.

**Comment by captnfab** [comment]
@grahamperrin this feature should now be available in Crappy FireTitle 0.1.7 !
Uppercase L in pattern should give the number of Loaded tabs (i.e. non-discarded tabs).
