### ISSUE TITLE
Multiprocess support?

### ISSUE THREAD

**Issue by hmijail** [captnfab/FireTitle#9]
I love this add-on, and I noticed that it still doesn't support multiprocess...
Any plans to fix that?

**Comment by captnfab** [comment]
Hi hmijail, and thanks for your interest.

I'd like to fix that, unfortunately, this would requires a rewrite of the add-on from xul api to web-extension framework (which seems fine and something TODO), but I don't think this framework allows an extension to access/change the browser's titlebar content. :(

If you know a way to change the window's title with webextensions, please tell me how to do that!

**Comment by hmijail** [comment]
In case it helps, I opened a feature request for such a WebExtension API. https://bugzilla.mozilla.org/show_bug.cgi?id=1333376

**Comment by captnfab** [comment]
I hope it will.
Thanks!

**Comment by captnfab** [comment]
I'm currently working on a web-extension version of this add-on.
It's not as polished as this xul-overlay version, but at least, we should be able to continue using most of the functionalities on most of the websites…
So, multiprocess support probably won't be implemented for this xul-overlay version, but will be supported on the webextension version.

**Comment by grahamperrin** [comment]
> … change the window's title … 

Mozilla bug [1333376 - Feature request: a WebExtension API to change the window title](https://bugzilla.mozilla.org/show_bug.cgi?id=1333376)

> RESOLVED FIXED in Firefox 56

**Comment by grahamperrin** [comment]
The resolution of Mozilla bug 1333376 was limited – to prefixing (prefacing). 

So we have a more recent bug, an enhancement request: 

- [1396010 - [webextensions] Feature request: Optionally display document's title in window's title](https://bugzilla.mozilla.org/show_bug.cgi?id=1396010)

**Comment by captnfab** [comment]
I'm closing this bug since it was about multiprocess support, which isn't relevant now that only webextensions are allowed.
